merge:
  whitelist:
    labels: ["automerge"]
  blacklist:
    labels: ["wip"]
  # one of: merge, squash, rebase
  method: squash
  # status checks required in addition to the ones defined in GitHub Branch Protection Rules
  required_statuses:
    - "continuous-integration/travis-ci/push"
    - "WIP"
  delete_after_merge: true
