pull_request_rules:
  - name: automatic merge when CI passes
    conditions:
      - author=supersandro2000
      - base=master
      - label!=wip
      - status-success=[AccessLint, continuous-integration/travis-ci/pr, Hound,WIP]
    actions:
      merge:
        method: squash

  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}

  - name: automatic merge for Dependabot pull requests on master
    conditions:
      - author=dependabot[bot]
      - base=master
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: squash
