os: linux
dist: bionic
language: shell
group: travis_latest
services:
  - docker

addons:
  apt:
    packages:
      # - docker-ce
      - jq

install:
  # needed for templating, currently not in use
  # - pip install --user j2cli

  # update docker for buildx
  - mkdir -p /etc/docker/
  - |
    echo -e '{"experimental": true}' | sudo tee /etc/docker/daemon.json
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt install -qy docker-ce
  # log into Docker HUB
  - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
  # enable multiarch
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  # create builder for buildx
  - docker buildx create --use --name build --node build --driver-opt network=host

env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    # - DOCKER_BUILDKIT=1

stages:
  - lint
  - Build base
  - build
  - manifest
  - scan

.template:
  - &build
    stage: build
    script:
      - if [[ $TRAVIS_CPU_ARCH == amd64 ]]; then docker run --rm --privileged multiarch/qemu-user-static --reset -p yes; fi
      - cd "$IMAGE"
      - make build;
      - docker images
    after_script:
      - if [[ $TRAVIS_BRANCH == master ]]; then
          make push;
          if [[ ${MANIFEST:-true} == true ]]; then
           make manifest;
          fi;
        fi

  - &manifest
    stage: manifest
    script:
      - cd "$IMAGE"
      - if [[ $TRAVIS_BRANCH == master ]]; then
          make manifest;
        fi

jobs:
  allow_failures:
    - stage: scan
    # remove when builds with .NET 3.1 hit stable
    - env: IMAGE=archisteamfarm VARIANT=alpine

  include:
    - stage: lint
      # install:
        # - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
      script:
        # - fossa init
        - make hadolint
        - make shellcheck
      # after_script:
      #   - fossa test

    - <<: *build
      stage: Build base
      env: IMAGE=base-alpine

    - <<: *build
      env: IMAGE=aports
    - <<: *build
      env: IMAGE=archisteamfarm VARIANT=alpine
    - <<: *build
      env: IMAGE=code-server-extra
    - <<: *build
      env: IMAGE=halcyon
    - <<: *build
      env: IMAGE=healthchecks VARIANTS=amd64 MANIFEST=false
    - <<: *build
      arch: arm64
      env: IMAGE=healthchecks VARIANTS=arm64 MANIFEST=false
    - <<: *build
      env: IMAGE=kibitzr
    - <<: *build
      env: IMAGE=open-web-calendar
    - <<: *build
      env: IMAGE=prerenderer
    - <<: *build
      env: IMAGE=reddiscord VARIANTS=amd64,armhf MANIFEST=false
    - <<: *build
      env: IMAGE=reddiscord TAGS=source VARIANTS=amd64,armhf VERSIONS=source MANIFEST=false
    - <<: *build
      arch: arm64
      env: IMAGE=reddiscord VARIANTS=arm64 MANIFEST=false
      before_script:
        - sudo apt install zip
    - <<: *build
      env: IMAGE=thelounge
    - <<: *build
      env: IMAGE=unbound
    - <<: *build
      env: IMAGE=zeronet

    - <<: *manifest
      env: IMAGE=archisteamfarm
      script:
        - if [[ $TRAVIS_BRANCH == master ]]; then
            cd archisteamfarm;
            make login;
            ./manifest.sh;
          fi
    - <<: *manifest
      env: IMAGE=healthchecks
    - <<: *manifest
      env: IMAGE=reddiscord

    - stage: scan
      cache:
        directories:
          - $HOME/.cache/trivy
      install:
        - make trivy
        - ./trivy --refresh --quiet || ./trivy --reset
      script:
        - ./trivy --exit-code 0 --severity HIGH     --quiet supersandro2000/archisteamfarm:alpine-latest
        - ./trivy --exit-code 1 --severity CRITICAL --quiet supersandro2000/archisteamfarm:alpine-latest
        - ./trivy --exit-code 0 --severity HIGH     --quiet supersandro2000/healthchecks:latest
        - ./trivy --exit-code 1 --severity CRITICAL --quiet supersandro2000/healthchecks:latest
        - ./trivy --exit-code 0 --severity HIGH     --quiet supersandro2000/kibitzr:latest
        - ./trivy --exit-code 1 --severity CRITICAL --quiet supersandro2000/kibitzr:latest
        - ./trivy --exit-code 0 --severity HIGH     --quiet supersandro2000/prerenderer:latest
        - ./trivy --exit-code 1 --severity CRITICAL --quiet supersandro2000/prerenderer:latest
        - ./trivy --exit-code 0 --severity HIGH     --quiet supersandro2000/unbound:latest
        - ./trivy --exit-code 1 --severity CRITICAL --quiet supersandro2000/unbound:latest
        - ./trivy --exit-code 0 --severity HIGH     --quiet supersandro2000/zeronet:latest
        - ./trivy --exit-code 1 --severity CRITICAL --quiet supersandro2000/zeronet:latest

# notifications:
#   webhooks:
#     - https://app.fossa.io/hooks/travisci
