dist: xenial
sudo: required
language: bash
services: 
  - docker
addons:
  apt:
    packages:
    - jq

env:
  matrix:
  - HADOLINT=${HOME}/hadolint

install:
  - curl -sLo ${HOME}/hadolint $(curl -s https://api.github.com/repos/hadolint/hadolint/releases/latest?access_token=${GITHUB_TOKEN} | jq -r '.assets | .[] | select(.name=="hadolint-Linux-x86_64") | .browser_download_url')
    && chmod 700 ${HADOLINT}

script:
  - git ls-files --exclude='*Dockerfile' --ignored | xargs --max-lines=1 ${HADOLINT}

jobs:
  include:
    - stage: deploy
      env:
        matrix:
        - IMAGE=archisteamfarm
        - IMAGE=freshrss
        - IMAGE=kibitzr
        - IMAGE=reddiscord
        - IMAGE=watchtower
      script:
        - cd ${IMAGE}
        - make build
        - docker images
      after_success:
        - if [ "${TRAVIS_BRANCH}" == "master" ] ; then
            make push ;
          fi
