dist: bionic
language: bash
group: travis_latest
services:
  - docker

# addons:
#   apt:
#     packages:
#     - docker-ce

env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    # - DOCKER_BUILDKIT=1

stages:
  - lint
  - build-base
  - build
  - manifest
  - scan

template:
  - &build
    stage: build
    script:
      - cd "$IMAGE"
      - if [[ -z $VARIANT ]]; then
          make build;
        else
          make build-$VARIANT;
        fi
      - docker images
    after_script:
      - if [[ $TRAVIS_BRANCH == master ]]; then
          if [[ -z $VARIANT ]]; then
            make push;
          else
            make push-$VARIANT;
          fi;
        fi

  - &manifest
    stage: manifest
    script:
      - cd "$IMAGE"
      - if [[ $TRAVIS_BRANCH == master ]]; then make manifest; fi

  - &scan-multi-arch
    stage: scan
    cache:
      directories:
        - $HOME/.cache/trivy
    install:
      - make trivy
    script:
      - ./trivy --refresh --quiet || ./trivy --reset
      - for arch in amd64 armhf arm64; do
        ./trivy --exit-code 0 --severity HIGH -quiet $IMAGE:$arch-latest ;
        ./trivy --exit-code 1 --severity CRITICAL --quiet $IMAGE:$arch-latest ;
        done

  - &scan
    stage: scan
    cache:
      directories:
        - $HOME/.cache/trivy
    install:
        - make trivy
    script:
      - ./trivy --refresh --quiet || ./trivy --reset
      - ./trivy --exit-code 0 --severity HIGH --quiet $IMAGE:latest
      - ./trivy --exit-code 1 --severity CRITICAL --quiet $IMAGE:latest

jobs:
  include:
    - stage: lint
      # install:
        # - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
      script:
        # - fossa init
        - make hadolint
        - make shellcheck
      # after_script:
      #   - fossa test

    - <<: *build
      stage: build-base
      env: IMAGE=base-alpine

    - <<: *build
      env: IMAGE=archisteamfarm VARIANT=alpine
    - <<: *build
      env: IMAGE=halcyon
    - <<: *build
      env: IMAGE=healthchecks
    - <<: *build
      env: IMAGE=kibitzr
    - <<: *build
      env: IMAGE=prerenderer
    - <<: *build
      env: IMAGE=reddiscord
    - <<: *build
      env: IMAGE=reddiscord TAGS=source VERSIONS=source
    - <<: *build
      env: IMAGE=unbound
    - <<: *build
      env: IMAGE=zeronet

    - <<: *manifest
      env: IMAGE=archisteamfarm
    - <<: *manifest
      env: IMAGE=reddiscord
    - <<: *manifest
      env: IMAGE=zeronet

    - <<: *scan-multi-arch
      env: IMAGE=supersandro2000/archisteamfarm VARIANT=alpine
      script:
        - ./trivy --refresh --quiet || ./travis --reset
        - for arch in master tag; do
          ./trivy --exit-code 0 --severity HIGH --quiet $IMAGE:$arch-alpine ;
          ./trivy --exit-code 1 --severity CRITICAL --quiet $IMAGE:$arch-alpine ;
          done
    - <<: *scan
      env: IMAGE=supersandro2000/healthchecks
    - <<: *scan-multi-arch
      env: IMAGE=supersandro2000/kibitzr
    - <<: *scan
      env: IMAGE=supersandro2000/prerenderer
    # - <<: *scan-multi-arch
    #   env: IMAGE=supersandro2000/reddiscord VARIANT=source
    - <<: *scan
      env: IMAGE=supersandro2000/unbound
    - <<: *scan-multi-arch
      env: IMAGE=supersandro2000/zeronet

# notifications:
#   webhooks:
#     - https://app.fossa.io/hooks/travisci
