os: linux
dist: bionic
language: shell
group: travis_latest
services:
  - docker

addons:
  apt:
    packages:
      # - docker-ce
      - jq

env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    # - DOCKER_BUILDKIT=1

stages:
  - lint
  - Build base
  - build
  - manifest
  - scan

.template:
  - &build
    stage: build
    script:
      - cd "$IMAGE"
      - make build;
      - docker images
    after_script:
      - if [[ $TRAVIS_BRANCH == master ]]; then
          make push;
          make manifest;
        fi

  - &manifest
    stage: manifest
    script:
      - cd "$IMAGE"
      - if [[ $TRAVIS_BRANCH == master ]]; then make manifest; fi

  - &scan-multi-arch
    stage: scan
    cache:
      directories:
        - $HOME/.cache/trivy
    install:
      - make trivy
    script:
      - ./trivy --refresh --quiet || ./trivy --reset
      - for arch in amd64 armhf arm64; do
        ./trivy --exit-code 0 --severity HIGH -quiet $IMAGE:$arch-latest ;
        ./trivy --exit-code 1 --severity CRITICAL --quiet $IMAGE:$arch-latest ;
        done

  - &scan
    stage: scan
    cache:
      directories:
        - $HOME/.cache/trivy
    install:
        - make trivy
    script:
      - ./trivy --refresh --quiet || ./trivy --reset
      - ./trivy --exit-code 0 --severity HIGH --quiet $IMAGE:latest
      - ./trivy --exit-code 1 --severity CRITICAL --quiet $IMAGE:latest

jobs:
  include:
    - stage: lint
      # install:
        # - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
      script:
        # - fossa init
        - make hadolint
        - make shellcheck
      # after_script:
      #   - fossa test

    - <<: *build
      stage: Build base
      env: IMAGE=base-alpine

    - <<: *build
      env: IMAGE=archisteamfarm VARIANT=alpine
    - <<: *build
      env: IMAGE=halcyon
    - <<: *build
      env: IMAGE=healthchecks VARIANTS=amd64,armhf
    - <<: *build
      arch: arm64
      env: IMAGE=healthchecks VARIANTS=arm64
    - <<: *build
      env: IMAGE=kibitzr
    - <<: *build
      env: IMAGE=prerenderer
    - <<: *build
      env: IMAGE=reddiscord VARIANTS=amd64,armhf
    - <<: *build
      env: IMAGE=reddiscord TAGS=source VARIANTS=amd64,armhf VERSIONS=source
    - <<: *build
      arch: arm64
      env: IMAGE=reddiscord VARIANTS=arm64
      install:
        - sudo apt install zip
    - <<: *build
      env: IMAGE=thelounge
    - <<: *build
      env: IMAGE=unbound
    - <<: *build
      env: IMAGE=zeronet

    - <<: *manifest
      env: IMAGE=archisteamfarm
      before_script:
        - if [[ $TRAVIS_BRANCH == master ]]; then  cd archisteamfarm; ./manifest.sh; fi
    - <<: *manifest
      env: IMAGE=reddiscord
    - <<: *manifest
      env: IMAGE=zeronet

    - <<: *scan-multi-arch
      env: IMAGE=supersandro2000/archisteamfarm VARIANT=alpine
      script:
        - ./trivy --refresh --quiet || ./travis --reset
        - for arch in master tag; do
          ./trivy --exit-code 0 --severity HIGH --quiet $IMAGE:$arch-alpine ;
          ./trivy --exit-code 1 --severity CRITICAL --quiet $IMAGE:$arch-alpine ;
          done
    - <<: *scan
      env: IMAGE=supersandro2000/healthchecks
    - <<: *scan-multi-arch
      env: IMAGE=supersandro2000/kibitzr
    - <<: *scan
      env: IMAGE=supersandro2000/prerenderer
    # - <<: *scan-multi-arch
    #   env: IMAGE=supersandro2000/reddiscord VARIANT=source
    - <<: *scan
      env: IMAGE=supersandro2000/unbound
    - <<: *scan-multi-arch
      env: IMAGE=supersandro2000/zeronet

# notifications:
#   webhooks:
#     - https://app.fossa.io/hooks/travisci
